// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package record

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson15d5d517DecodeGithubComSsfilatovTsPkgRecord(in *jlexer.Lexer, out *InternalRecord) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Email":
			out.Email = string(in.String())
		case "SessionID":
			out.SessionID = string(in.String())
		case "Timestamp":
			out.Timestamp = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson15d5d517EncodeGithubComSsfilatovTsPkgRecord(out *jwriter.Writer, in InternalRecord) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Email\":"
		out.RawString(prefix[1:])
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"SessionID\":"
		out.RawString(prefix)
		out.String(string(in.SessionID))
	}
	{
		const prefix string = ",\"Timestamp\":"
		out.RawString(prefix)
		out.Int64(int64(in.Timestamp))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v InternalRecord) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson15d5d517EncodeGithubComSsfilatovTsPkgRecord(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v InternalRecord) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson15d5d517EncodeGithubComSsfilatovTsPkgRecord(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *InternalRecord) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson15d5d517DecodeGithubComSsfilatovTsPkgRecord(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *InternalRecord) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson15d5d517DecodeGithubComSsfilatovTsPkgRecord(l, v)
}
func easyjson15d5d517DecodeGithubComSsfilatovTsPkgRecord1(in *jlexer.Lexer, out *APIRecord) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "email":
			out.Email = string(in.String())
		case "sessionId":
			out.SessionID = string(in.String())
		case "eventTime":
			out.EventTime = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson15d5d517EncodeGithubComSsfilatovTsPkgRecord1(out *jwriter.Writer, in APIRecord) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix[1:])
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"sessionId\":"
		out.RawString(prefix)
		out.String(string(in.SessionID))
	}
	{
		const prefix string = ",\"eventTime\":"
		out.RawString(prefix)
		out.String(string(in.EventTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v APIRecord) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson15d5d517EncodeGithubComSsfilatovTsPkgRecord1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v APIRecord) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson15d5d517EncodeGithubComSsfilatovTsPkgRecord1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *APIRecord) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson15d5d517DecodeGithubComSsfilatovTsPkgRecord1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *APIRecord) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson15d5d517DecodeGithubComSsfilatovTsPkgRecord1(l, v)
}
